name: covid
channels:
  - conda-forge
dependencies:
  - python=3.6
  - geopandas=0.7
  - jupyter
  - matplotlib
  - numba
  - numpy
  - pandas
  - seaborn

  # Development
  - pre-commit=2.3.0
  - black
  - isort
  - flake8
  - mypy
  - pytest
